# CODE GENERATED BY ChatGPT
# I may re-create the weather app myself in a separate file
# or adapt the current code some day.

import requests
import tkinter as tk
import os
import webbrowser

root = tk.Tk()
root.title("Simple Weather App by Slend and ChatGPT")
root.geometry("450x225")
root.resizable(False, False)

label = tk.Label(root, text="Please enter your postcode/zip code.")
label.pack()

entry = tk.Entry(root)
entry.pack()

def callback(url):
  webbrowser.open_new(url)

def get_weather():
  postal_code = entry.get()
  api_key = os.environ["api_key"]
  url = f"https://api.weatherbit.io/v2.0/current?postal_code={postal_code}&key={api_key}"
  response = requests.get(url)

  print("New request made")
  
  data = response.json()
  ob_time = data["data"][0]["ob_time"]
  temperature = data["data"][0]["temp"]
  description = data["data"][0]["weather"]["description"]
  city_name = data["data"][0]["city_name"]
  
  print(f"Request made for {city_name} ({postal_code}).")
  
  country_code = data["data"][0]["country_code"]
  wind_dir_full = data["data"][0]["wind_cdir_full"]
  sunrise = data["data"][0]["sunrise"]
  sunset = data["data"][0]["sunset"]
  wind_speed = data["data"][0]["wind_spd"]
  precip = data["data"][0]["precip"]
  visibility = data["data"][0]["vis"]
  
  print(f"Temp = {temperature}")
  print(f"City name = {city_name}")
  print(f"Country code = {country_code}")
  print(f"Desc = {description}")
  print(f"Wind direction in full = {wind_dir_full}")
  print(f"Sunrise time = {sunrise}")
  print(f"Sunset time = {sunset}")
  print(f"Wind speed (rounded to 2 d.p. in the GUI) = {wind_speed}mph")
  print(f"Amount of Precipitation in the last hour = {precip}mm")
  print(f"Visibility = {visibility}km")
  print(f"Observation time and date: {ob_time}")
  
  label2.config(text=f"Weather Information for {city_name} ({country_code}) as of {ob_time}.\nTemperature: {temperature}°C\nDescription: {description}\nWind direction: {wind_dir_full.capitalize()} @ {round(wind_speed, 2)}mph\nSunrise: {sunrise} | Sunset: {sunset}\nAmount of precipitation in the last hour: {precip}mm\nVisibility: {visibility}km")

button = tk.Button(root, text="Get weather information.", command=get_weather)
button.pack()

label2 = tk.Label(root, text="")
label2.pack()

root.mainloop()